CREATE TABLE IF NOT EXISTS cidade (
  id INT(11) NOT NULL AUTO_INCREMENT,
  codigo_cidade INT(11) NOT NULL,
  nome VARCHAR(255) NOT NULL,
  pais VARCHAR(2) NOT NULL,
  latitude DECIMAL(8,4) NOT NULL,
  longitude DECIMAL(8,4) NOT NULL,
  data_criacao DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
